export const GET_CAR_MODEL = 'GET_CAR_MODEL';
export const GET_ALL_CAR_MODELS_REQUEST = 'GET_ALL_CAR_MODELS_REQUEST';
export const GET_ALL_CAR_MODELS_SUCCESS = 'GET_ALL_CAR_MODELS_SUCCESS';
export const DELETE_CAR_MODELS_REQUEST = 'DELETE_CAR_MODELS_REQUEST';
