export const GET_CAR = 'GET_CAR';
export const GET_ALL_CARS_REQUEST = 'GET_ALL_CARS_REQUEST';
export const GET_ALL_CARS_SUCCESS = 'GET_ALL_CARS_SUCCESS';
export const GET_CAR_REQUEST = 'GET_CAR_REQUEST';
export const GET_CAR_SUCCESS = 'GET_CAR_SUCCESS';
