export const GET_CAR = 'GET_CAR';
export const GET_ALL_CARS_REQUEST = 'GET_ALL_CARS_REQUEST';
export const GET_ALL_CARS_SUCCESS = 'GET_ALL_CARS_SUCCESS';
export const DELETE_CARS_REQUEST = 'DELETE_CARS_REQUEST';
