export const GET_CAR_MAKES = 'GET_CAR_MAKES';
export const GET_ALL_CAR_MAKES_REQUEST = 'GET_ALL_CAR_MAKES_REQUEST';
export const GET_ALL_CAR_MAKES_SUCCESS = 'GET_ALL_CAR_MAKES_SUCCESS';
export const DELETE_CAR_MAKES_REQUEST = 'DELETE_CAR_MAKES_REQUEST';
export const DELETE_CAR_MAKES_SUCCESS = 'DELETE_CAR_MAKES_SUCCESS';
export const GET_CAR_MAKE_REQUEST = 'GET_CAR_MAKE_REQUEST';
export const GET_CAR_MAKE_SUCCESS = 'GET_CAR_MAKE_SUCCESS';
