/*
 *
 * CarPhotoCreate constants
 *
 */

export const CREATE_CAR_PHOTO_REQUEST = 'CREATE_CAR_PHOTO_REQUEST';
export const GET_ALL_CARS_REQUEST = 'GET_ALL_CARS_REQUEST';
export const GET_ALL_CARS_SUCCESS = 'GET_ALL_CARS_SUCCESS';
export const CREATE_CAR_PHOTO_SUCCESS = 'CREATE_CAR_PHOTO_SUCCESS';
