export const GET_REVIEW = 'GET_REVIEW';
export const GET_ALL_REVIEWS_REQUEST = 'GET_ALL_REVIEWS_REQUEST';
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS';
export const DELETE_REVIEWS_REQUEST = 'DELETE_REVIEWS_REQUEST';
